// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MvcWeb.Migrations
{
    [DbContext(typeof(MvcWebContext))]
    [Migration("20210702173852_ProductModelBuild")]
    partial class ProductModelBuild
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("MvcWeb.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("TEXT");

                    b.Property<string>("bannerContentDown")
                        .HasColumnType("TEXT");

                    b.Property<string>("bannerContentUp")
                        .HasColumnType("TEXT");

                    b.Property<int>("bannerIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("bannerState")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Banner");
                });

            modelBuilder.Entity("MvcWeb.Models.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("productDescription")
                        .HasColumnType("TEXT");

                    b.Property<int>("productIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("productNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("productPicture")
                        .HasColumnType("TEXT");

                    b.Property<string>("productPosition")
                        .HasColumnType("TEXT");

                    b.Property<string>("productPs")
                        .HasColumnType("TEXT");

                    b.Property<string>("productUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("productId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("MvcWeb.Models.SubBoard", b =>
                {
                    b.Property<int>("Sub_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sub_Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sub_Link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sub_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Sub_Id");

                    b.ToTable("SubBoard");
                });
#pragma warning restore 612, 618
        }
    }
}
